version: '3.2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${CONFLUENT_PLATFORM_VERSION:-3.2.1}
    hostname: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - streaming
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION:-3.2.1}
    hostname: kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
     - 9092:9092
    networks:
      - streaming

  connector:
    image: openfaas/kafka-connector:0.3.3
    hostname: kafka-connector
    environment:
      gateway_url: http://gateway:8080
      topics: "faas-request,"
      print_response: "true"
      print_response_body: "true"
      basic_auth: "true"
      secret_mount_path: "/run/secrets/"
    secrets:
      - basic-auth-password
      - basic-auth-user
    networks:
      - streaming
      - func_functions

networks:
  streaming:
    driver: overlay
    attachable: true
  func_functions:
    external: true

secrets:
    basic-auth-user:
        external: true
    basic-auth-password:
        external: true
